/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2020-02-20 17:37:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div id=\"navbar\" class=\"navbar navbar-default          ace-save-state\">\r\n");
      out.write("\t<div class=\"navbar-container ace-save-state\" id=\"navbar-container\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"navbar-toggle menu-toggler pull-left\"\r\n");
      out.write("\t\t\tid=\"menu-toggler\" data-target=\"#sidebar\">\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Toggle sidebar</span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navbar-header pull-left\">\r\n");
      out.write("\t\t\t<a href=\"index.html\" class=\"navbar-brand\"> <small> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-leaf\"></i> Ace Admin\r\n");
      out.write("\t\t\t</small>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navbar-buttons navbar-header pull-right\" role=\"navigation\">\r\n");
      out.write("\t\t\t<ul class=\"nav ace-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"grey dropdown-modal\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ace-icon fa fa-tasks\"></i> <span class=\"badge badge-grey\">4</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-header\"><i class=\"ace-icon fa fa-check\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t4 Tasks to complete</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-navbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Software Update</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\">65%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 65%\" class=\"progress-bar\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Hardware Upgrade</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\">35%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 35%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"progress-bar progress-bar-danger\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Unit Testing</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\">15%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 15%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"progress-bar progress-bar-warning\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\">Bug Fixes</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\">90%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-mini progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 90%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"progress-bar progress-bar-success\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-footer\"><a href=\"#\"> See tasks with\r\n");
      out.write("\t\t\t\t\t\t\t\tdetails <i class=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"purple dropdown-modal\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ace-icon fa fa-bell icon-animated-bell\"></i> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"badge badge-important\">8</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-header\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ace-icon fa fa-exclamation-triangle\"></i> 8 Notifications\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-navbar navbar-pink\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs no-hover btn-pink fa fa-comment\"></i> New\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tComments\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span> <span class=\"pull-right badge badge-info\">+12</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs btn-primary fa fa-user\"></i> Bob just signed\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tup as an editor ...\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs no-hover btn-success fa fa-shopping-cart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tNew Orders\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span> <span class=\"pull-right badge badge-success\">+8</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs no-hover btn-info fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tFollowers\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span> <span class=\"pull-right badge badge-info\">+11</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-footer\"><a href=\"#\"> See all\r\n");
      out.write("\t\t\t\t\t\t\t\tnotifications <i class=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"green dropdown-modal\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ace-icon fa fa-envelope icon-animated-vertical\"></i> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"badge badge-success\">5</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-header\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ace-icon fa fa-envelope-o\"></i> 5 Messages</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-navbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"template/admin/assets/images/avatars/avatar.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-photo\" alt=\"Alex's Avatar\" /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-body\"> <span class=\"msg-title\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"blue\">Alex:</span> Ciao sociis natoque penatibus et\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tauctor ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>a moment\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"template/admin/assets/images/avatars/avatar3.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-photo\" alt=\"Susan's Avatar\" /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-body\"> <span class=\"msg-title\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"blue\">Susan:</span> Vestibulum id ligula porta felis\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\teuismod ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>20 minutes\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"template/admin/assets/images/avatars/avatar4.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-photo\" alt=\"Bob's Avatar\" /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-body\"> <span class=\"msg-title\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"blue\">Bob:</span> Nullam quis risus eget urna mollis\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tornare ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>3:15 pm</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"template/admin/assets/images/avatars/avatar2.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-photo\" alt=\"Kate's Avatar\" /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-body\"> <span class=\"msg-title\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"blue\">Kate:</span> Ciao sociis natoque eget urna\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tmollis ornare ...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>1:33 pm</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"clearfix\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"template/admin/assets/images/avatars/avatar5.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-photo\" alt=\"Fred's Avatar\" /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"msg-body\"> <span class=\"msg-title\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"blue\">Fred:</span> Vestibulum id penatibus et auctor\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span class=\"msg-time\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-clock-o\"></i> <span>10:09 am</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown-footer\"><a href=\"inbox.html\"> See all\r\n");
      out.write("\t\t\t\t\t\t\t\tmessages <i class=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"light-blue dropdown-modal\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\thref=\"#\" class=\"dropdown-toggle\"> <img class=\"nav-user-photo\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"template/admin/assets/images/avatars/user.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Jason's Photo\" /> <span class=\"user-info\"> <small>Welcome,</small>\r\n");
      out.write("\t\t\t\t\t\t\tJason\r\n");
      out.write("\t\t\t\t\t</span> <i class=\"ace-icon fa fa-caret-down\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\tclass=\"user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"ace-icon fa fa-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\tSettings\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"profile.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ace-icon fa fa-user\"></i> Profile\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"ace-icon fa fa-power-off\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\tLogout\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.navbar-container -->\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
